import React from 'react';
import { Users, ArrowRight } from 'lucide-react';

/**
 * GroupDecisionOptions
 * Displays high-level group strategy options generated by the StoryAgent / GameMaster.
 * 
 * Props:
 * - options: Array of strings or objects { label, value }
 * - onSelect: (optionValue) => void
 */
export default function GroupDecisionOptions({ options, onSelect }) {
    if (!options || options.length === 0) return null;

    return (
        <div className="fixed bottom-32 left-1/2 -translate-x-1/2 z-50 flex flex-col items-center gap-3 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="bg-slate-900/90 backdrop-blur-md border border-amber-500/50 px-4 py-1 rounded-full flex items-center gap-2 shadow-lg shadow-black/50">
                <Users size={14} className="text-amber-500" />
                <span className="text-xs font-bold text-amber-100 font-tome-header uppercase tracking-wider">
                    Group Decision Needed
                </span>
            </div>

            <div className="flex gap-3">
                {options.map((option, idx) => {
                    const label = typeof option === 'string' ? option : option.label;
                    const value = typeof option === 'string' ? option : option.value;

                    return (
                        <button
                            key={idx}
                            onClick={() => onSelect(value)}
                            className="
                                group relative overflow-hidden
                                bg-slate-950 border border-slate-600 hover:border-amber-500 
                                text-slate-300 hover:text-white
                                py-3 px-6 rounded-lg 
                                font-bold font-tome-body text-sm
                                shadow-xl hover:shadow-amber-900/20 hover:-translate-y-1 transition-all duration-200
                                flex items-center gap-2
                            "
                        >
                            <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent pointer-events-none" />
                            <span className="relative z-10">{label}</span>
                            <ArrowRight size={14} className="opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all text-amber-500 relative z-10" />
                        </button>
                    );
                })}
            </div>
        </div>
    );
}
