import { AIService } from "../services/AIService";
import { formatModuleContext } from '../data/modules_data.js';

// LOCKED BY USER REQUEST (2025-12-10). DO NOT EDIT WITHOUT EXPLICIT PERMISSION.
// UPDATED 2025-12-15: Added encounter balance level reference (user-approved)
/**
 * GameMasterAgent: The Referee
 * Responsible for mechanics, rules enforcement, and state updates.
 * Inputs: Narrative Text + Current Stats
 * Outputs: JSON Updates (HP, Options, Loot)
 */
export class GameMasterAgent {
    constructor(options = {}) {
        this.aiService = new AIService(options);
    }

    async _generate(prompt) {
        try {
            const result = await this.aiService.generate(prompt, {
                isJson: true,
                model: "gemini-2.0-flash-exp" // Use the same model as intended
            });

            return {
                text: result.text,
                usage: result.usage
            };
        } catch (error) {
            console.error("[GameMasterAgent] Generation Failed:", error);
            throw error;
        }
    }

    /**
     * Analyzes the narrative to produce game state updates.
     * @param {Object} context
     * @param {string} context.narrative - The text generated by StoryAgent.
     * @param {number} context.level - Current party level (for scaling).
     * @param {Array} context.partyStatus - Array of character objects (HP, Name).
     * @returns {Promise<Object>} JSON object with hp_updates, options, loot.
     */
    async analyzeState(context) {
        const { narrative, level, partyStatus, moduleId = null, currentAct = 1, lootGuidelines = '' } = context;

        // Generate module plot context if available
        const plotContext = moduleId ? formatModuleContext(moduleId, currentAct) : '';

        const systemPrompt = `
        You are the **Game Master** (Mechanics Agent) for a D&D-style game.
        **CRITICAL: ALL TEXT OUTPUT MUST BE IN TRADITIONAL CHINESE (繁體中文 - 台灣正體). NO SIMPLIFIED CHINESE. NO ENGLISH.**
        **嚴格遵守：所有輸出內容必須使用繁體中文（台灣習慣）。絕對禁止出現簡體中文。**
        Your job is to read the narrative and translate it into game mechanics, risks, and agent signals.

        === MULTI-AGENT REASONING RULES ===
        1. Cross-Agent Integration
           - Detect implied danger from StoryAgent (creatures, traps, tension).
           - Use CartographerAgent outputs (if provided in context) to apply environmental effects.
           - Infer mechanical outcomes even if not explicitly stated (Autonomous Rule Completion).

        2. Autonomous Rule Completion
           - If narrative suggests danger but no hit is mentioned, infer a risk roll or save.
           - If an enemy is implied to be strong, infer higher damage.
           - If players do something clever, award advantage or XP.

        3. Signal Output (Crucial for other Agents)
           - **threat_level**: (None / Low / High / Deadly) -> Tells StoryAgent/CharAgent how tense to react.
           - **pacing_signal**: (Build-up / Climax / Resolution) -> Tells OptionsAgent what kind of options to offer.
           - **mechanical_opportunity**: (e.g., "Enemy Prone", "Stealth Possible") -> Tells StoryAgent/OptionsAgent to use this.
        
        [CURRENT CONTEXT]
        Party Level: ${level}
        Party Status: ${JSON.stringify(partyStatus)}
        
        [NARRATIVE INPUT]
        "${narrative}"

        === LOGIC SYNCHRONIZATION ===
        1. **Dice Roll Priority**: If the narrative contains explicit dice rolls like \`[傷害: ... = 8]\` or \`[Damage: ... = 8]\`, you MUST use that exact value for HP updates.
        2. **Consistency**: Do not re-roll or invent new damage if it was already stated in the text.
        3. **Fallback**: Only calculate new damage if the narrative implies injury but provides no specific numbers.

${plotContext ? `[MODULE PLOT CONTEXT]\n${plotContext}\n` : ''}
        [TASKS]
        1. **HP Analysis**: Calculate damage based on weapon type and Level ${level}.
           === DAMAGE DICE REFERENCE ===
           - Light Weapons (Dagger, Shortsword): 1d6+Mod (avg 4-7)
           - Medium Weapons (Longsword, Mace): 1d8+Mod (avg 5-9)
           - Heavy Weapons (Greatsword, Greataxe): 2d6+Mod (avg 8-12)
           - Ranged (Longbow, Crossbow): 1d8+Mod (avg 5-9)
           - Cantrips: 1d10 (avg 5-6)
           - Low Spells (1-3): 2d6 to 4d6 (avg 7-14)
           - High Spells (4+): 5d6 to 8d6 (avg 17-28)
           
           === LEVEL SCALING ===
           - Level 1-4: Base damage, enemies deal 3-10 dmg
           - Level 5-10: +50% damage, enemies deal 10-25 dmg
           - Level 11+: Double damage, enemies deal 20-50 dmg
           
        2. **Signals**: Generate the 3 signals (Threat, Pacing, Opportunity).
        3. **Loot**: Generate loot if thematically appropriate.
           - **Quest Items**: Mark as \`isQuestItem: true\`. Must aid story progression.
           - **General Loot**: Gold, potions, generic gear.
           - **Class Items**: If an item fits a specific party member (e.g. Plate for Paladin), target them.
           - **Restock Priority**: 
             - Check player HP status. If critical, prioritize dropping Healing Potions.
             - **Level Scaling**: 
               - Lv 1-4: Dropping 'Potion of Healing' (Common).
               - Lv 5+: Dropping 'Potion of Greater Healing' (Uncommon).
             - **Quantity**: 
               - Relaxed/Low Threat: Drop 2-3 consumables.
               - Grim/High Threat: Scarcity rules apply (0-1 relevant item).

${lootGuidelines ? `${lootGuidelines}\n` : ''}

        [OUTPUT SCHEMA]
        {
            "hp_updates": { "character_id_or_name": -5 },
            "inventory_updates": [
                {
                    "character": "CharacterName",
                    "item": "Potion of Healing",
                    "change": -1, // Negative for used/lost, Positive for gained
                    "reason": "Used during combat"
                }
            ],
            "loot": [
                {
                    "name": "Item Name",
                    "type": "weapon|armor|consumable|quest|misc",
                    "description": "Flavor text",
                    "isQuestItem": true, // true if critical for plot
                    "targetCharacter": "CharacterName" // Optional: Force allocation to specific char (e.g. User)
                }
            ],
            "xp": 0,
            "signals": {
                "threat_level": "Low",
                "pacing_signal": "Build-up",
                "mechanical_opportunity": "None"
            }
        }
        `;

        try {
            const result = await this._generate(systemPrompt);
            return { data: JSON.parse(result.text), usage: result.usage };
        } catch (error) {
            console.error("GameMasterAgent Error:", error);
            // Fallback options if analysis fails
            return {
                data: {
                    signals: { threat_level: "None", pacing_signal: "Build-up", mechanical_opportunity: "None" },
                    hp_updates: {},
                    new_mobs: [],
                    loot_drops: []
                },
                usage: null
            };
        }
    }
    /**
     * Resolves a user's action by parsing intent and applying game rules.
     * @param {Object} context
     * @param {string} context.narrative - The *previous* narrative context (for situation awareness).
     * @param {string} context.action - The user's declared action.
     * @param {number} context.level - Current party level.
     * @param {Array} context.partyStatus - Array of character objects.
     * @returns {Promise<Object>} The resolved outcome (success/fail, rolls, damage, description).
     */
    async resolveAction(context) {
        const { narrative, action, level, partyStatus } = context;

        const systemPrompt = `
        You are the **Game Master** (Rules Engine) for a D&D-style game.
        Your task is to RESOLVE the player's action physically and mechanically.
        Do NOT write a story. Output the RAW MECHANICAL RESULT.

        [CONTEXT]
        Previous Situation: "${narrative.slice(-2000)}"
        Party Level: ${level}
        Party Status: ${JSON.stringify(partyStatus)}

        [PLAYER ACTION]
        "${action}"

        [TASK]
        1. **Intent Analysis**: What is the player trying to do? (Attack, Cast Spell, Hiding, Persuasion?)
           - **PLOT CHECK**: If the action matches a specific plot goal mentioned in the context (e.g., "Pull the lever", "Destroy the gem"), prioritize that interpretation over a generic attack.
        2. **Difficulty Assessment**: 
           - Attack: Assume standard Enemy AC based on Level (Lvl 1-4: AC 12-14, Lvl 5+: AC 15-18).
           - Skill Check: Set DC (Easy: 10, Medium: 15, Hard: 20).
        3. **Resolution**:
           - ROLL D20 for the main check.
           - Add a reasonable modifier (Assume +5 for Lvl 3, +7 for Lvl 5).
           - Compare vs AC/DC.
           - If Success and it's an Attack, ROLL DAMAGE.
             - Light Weapon: 1d6+3
             - Heavy Weapon: 2d6+3
             - Spell: 1d10 (Cantrip) or 4d6 (Level 1-2 Spell)
        4. **Consequences**:
           - If Failed: What happens? (Miss, Counter-attack, Trap triggers?)

        5. **COMPANION / PET ADJUDICATION (IMPORTANT)**:
           - If the action is a "Companion Order" (Option D or similar):
           - **Type A: Assist/Help**: If ordering to "Distract", "Scout", or "Help" -> Award **Advantage** on the next check (Mechanically: success=true, no damage, but "system_fact" notes Advantage granted).
           - **Type B: Attack**: If ordering to "Attack" -> Roll independent damage (Low: 1d4+2, High: 1d6+3). treat as a bonus attack.
           - Output the companion's success/failure clearly in "outcome_description".


        [OUTPUT SCHEMA - TRADITIONAL CHINESE]
        {
            "intent": "Attack" | "Skill" | "Move" | "Misc",
            "target": "Target Name",
            "check": "Attack Roll" | "Stealth Check", 
            "roll_formula": "1d20+5",
            "roll_result": 18,
            "target_value": 14,
            "success": true,
            "damage": 6, // 0 if miss or non-combat
            "damage_type": "Slashing" | "Fire",
            "outcome_description": "妳不僅擊中了地精，還砍斷了它的盾牌...", // Detailed mechanical outcome description (Traditional Chinese, 50-80 chars)
            "system_fact": "Player rolled 18 vs AC 14. Hit for 6 Slashing damage." // Fact for StoryAgent
        }
        `;

        try {
            const result = await this._generate(systemPrompt);
            const text = result.text;
            const jsonText = text.replace(/^```json/gm, "").replace(/^```/gm, "").trim();
            return JSON.parse(jsonText);
        } catch (error) {
            console.error("GM Rule Resolution Error:", error);
            // Fallback for safety
            return {
                intent: "Unknown",
                success: true,
                roll_result: 15,
                outcome_description: "行動已執行。",
                system_fact: "The action was resolved successfully."
            };
        }
    }
}
